### ISSUE TITLE
Question: how to read the tag from Rockwelll Micro 850 (2080-LC50-24QWB)?

### ISSUE THREAD

**Issue by abonent312** [libplctag/libplctag#157] opened 2020-07-16 22:12 UTC
Hi! Pls help me to build the correct path-string for Rockwelll Micro 850 (2080-LC50-24QWB)?
I used the next form (in src/examples/simple.c):
`protocol=ab-eip&gateway=192.168.5.20&path=1,0&cpu=micro800&elem_count=1&elem_size=4&debug=4&name=L19_0_8_DispActWeight[1]`
it gives error:

`2020-06-16 21:26:48.097 thread(2) tag(0) WARN recv_forward_open_resp:2193 Forward Open command failed, response code: Port Not Available (1)
2020-06-16 21:26:48.097 thread(2) tag(0) WARN recv_forward_open_resp:2214 CIP error code 1!
2020-06-16 21:26:48.097 thread(2) tag(0) INFO recv_forward_open_resp:2234 Done.`

(the 
[libplctag_1_0.txt](https://github.com/libplctag/libplctag/files/4934549/libplctag_1_0.txt)
full log is attached)

I tried different combinations for "path=x,y" : 2,0 3,0 4,0. It helps a bit, session is created
`2020-06-16 21:25:58.708 thread(3) tag(0) DETAIL session_create_request:2384 Done.
`

but after that I see another error (TIMEOUT):
`2020-06-16 21:25:58.710 thread(3) tag(0) DETAIL send_eip_request:1728 Done.
2020-06-16 21:25:58.744 thread(3) tag(0) INFO send_forward_open_req_ex:2156 Done
2020-06-16 21:25:58.744 thread(3) tag(0) INFO recv_forward_open_resp:2169 Starting
2020-06-16 21:25:58.745 thread(3) tag(0) DETAIL recv_eip_response:1748 Starting.
2020-06-16 21:26:03.685 thread(1) tag(0) WARN plc_tag_create:560 Timeout waiting for tag to be ready!
2020-06-16 21:26:03.686 thread(1) tag(0) DETAIL ab_tag_abort:685 Starting.
2020-06-16 21:26:03.686 thread(1) tag(0) DETAIL ab_tag_abort:701 Done.
2020-06-16 21:26:03.686 thread(1) tag(0) WARN plc_tag_create:567 Error PLCTAG_ERR_TIMEOUT while trying to create tag!
`
thank you!

**Comment by kyle-github** [comment] 2020-07-17 03:51
Hi,

Thanks for using the library.  The error log is very helpful, thanks for including it.  It is hard to see in the output:

```text
2020-06-16 22:19:11.555 thread(1) tag(0) WARN ab_tag_create:371 A path is not supported for this PLC type.
```

Leave the path off completely, and it should connect if you have all the other parts correct.   The Micro800 series is weird.   These PLCs only support a limited subset of the command protocol used with ControlLogix systems.

```text
protocol=ab-eip&gateway=192.168.5.20&cpu=micro800&elem_count=1&elem_size=4&debug=4&name=L19_0_8_DispActWeight[1]
```

This should probably be a fatal error instead of a warning.   It looks like the code goes on to try to make a connection to the PLC, which then fails some time several milliseconds later.

I am going to mark this as a bug.   The error should be a lot more clear and the code should not continue past the point that the error is logged.

Thanks for reporting this!

**Comment by kyle-github** [comment] 2020-07-17 03:52
BUG: When a path is passed to a Micr800, cause plc_tag_tag() to fail at the point that the path is checked and the warning logged.

**Comment by abonent312** [comment] 2020-07-17 08:03
If I remove "path"-sentence completely and use the string:
`protocol=ab-eip&gateway=192.168.5.20&cpu=micro800&elem_count=1&elem_size=4&debug=4&name=L19_0_8_DispActWeight[1]`
I see another error:
`2020-06-17 07:51:32.727 thread(3) tag(0) WARN recv_forward_open_resp:2193 Forward Open command failed, response code: Invalid Segment in Connection Path (1)`
 (log is attached 
[libplctag_no_path.txt](https://github.com/libplctag/libplctag/files/4936456/libplctag_no_path.txt)
 )

What are the segments of the "Connection path"? What could be probably wrong: "elem_count", "elem_size" or "name" ?

I also read all the available classes by Ethernet/IP (by another library). I assume here is all the settings of PLC... (if it helps)
[plc_5_20_scan_09_08.txt](https://github.com/libplctag/libplctag/files/4936477/plc_5_20_scan_09_08.txt)

thank you for your support!!

**Comment by kyle-github** [comment] 2020-07-17 16:41
This is confusing to me.  There is no connection path in the Forward Open packet!

I will need to experiment with older versions of the library to see if there is something that changed.   I think you have found a bug!

Which version of the library are you using?

**Comment by abonent312** [comment] 2020-07-17 21:04
the lastest commit from master..
d4afe282c49574f5ffec5db345303a552acbe089

**Comment by kyle-github** [comment] 2020-07-18 23:11
This is a regression that was added when I refactored some of the path handling in order to fix some of the DH+ support.   

I think I have this fixed on the prerelease branch.   Can you check that out and try it?   Thanks again for reporting this!

**Comment by abonent312** [comment] 2020-07-20 14:44
Hi Kyle, it works now.
[libplctag_no_path_7b43fd9.txt](https://github.com/libplctag/libplctag/files/4948351/libplctag_no_path_7b43fd9.txt)

`2020-06-20 14:39:48.286 thread(1) tag(11) INFO plc_tag_read:1073 Done
Tag has 1 elements each of 4 bytes.
data[0]=3922`

3922 is a correct value, thank you!

the path I used:
`protocol=ab-eip&gateway=192.168.5.20&cpu=micro800&elem_count=1&elem_size=4&debug=4&name=L19_0_8_DispActWeight[1]`

**Closed as completed** 2020-07-25 14:39 UTC
Labels: bug
