### ISSUE TITLE
Modbus doesn't recover after loss of communication

### ISSUE THREAD

**Issue by GitHubDragonFly** [libplctag/libplctag#195] opened 2020-09-03 23:45 UTC
As tested on Android, the same code structure is used for polling AB (MicroLogix 1100) and Modbus (simulator).

After loss of communication, Modbus did re-establish the connection, was polling the device but no values were returned.

After loss of communication, AB did re-establish the connection, was polling the device and values were returned.

I could blame either Android or the simulator but that wouldn't explain why AB was working.

**Comment by kyle-github** [comment] 2020-09-04 14:48
Hmm.   That is not good. Thanks for bringing this up.  I will investigate as soon as I can.  I will mark this as a bug until it is fixed.

**Comment by GitHubDragonFly** [comment] 2020-09-05 22:28
Just some additional info for Modbus, after re-establishing the connection it did start sending requests but it was painfully slow.

**Comment by kyle-github** [comment] 2020-09-06 13:35
Thanks for the update.  I am modifying the async_stress.c test to try to reproduce this.

How are you causing communications to fail?   I am going to kill the Modbus simulator and restart it.

**Comment by kyle-github** [comment] 2020-09-06 14:39
I was able to reproduce this.   It was due to an incomplete set of code that handled drop outs.  A flag was reset, but not a buffer size and so it keep returning the same response packet over and over without ever clearing it.

This is fixed in 2.1.17.

**Closed as completed** 2020-09-06 14:52 UTC
Labels: bug

**Comment by GitHubDragonFly** [comment] 2020-10-25 07:27
Just so you know, your README.md file has an extra letter "m" on the "releases" link within "How to Contribute" paragraph.
It might just confuse people if they are to click it.
Your other "releases" link works fine (within "How to Get The Code" paragraph).

There was no need to start a new issue because of this, so I will delete this post later on when you manage to correct it.

**Comment by kyle-github** [comment] 2020-10-25 09:45
Thanks! I fixed it directly in GitHub.   I will go through the other links when I can in the morning.  Off to bed now!
