### ISSUE TITLE
Status is still pending when read/write completed events are raised

### ISSUE THREAD

**Issue by Joylei** [libplctag/libplctag#338] opened 2022-01-13 14:06 UTC
I did multithreading bench testing and I found in the version v2.4.9 there are chances that status is still pending when read/write completed events are raised.
Then I did more testing with previous versions.
It seems that it happens from v2.4.5.

- platform: windows 10
- protocol=ab-eip&plc=controllogix

**Comment by kyle-github** [comment] 2022-01-13 23:11
Hi, can you give me more information about which status and the actions your program is taking in what order?

Do you mean the status as returned in a callback or the status from plc_tag_status()?

**Comment by Joylei** [comment] 2022-01-14 01:21
yes, I mean the status as returned in a callback.

I wrote the code in rust.
the async code is that:
- acquire a mutex lock for tag_id (in rust), ensure only one action can be performed for a tag. since it's multithreading, different tags have different mutex locks.
- read a tag: plc_tag_read(tag_id, 0)
- resume if a callback is received and the event is read completed,return the status from callback. because there is no way to pass in user data to a callback, there is a global state to track the callback, but it's lock protected.
- assert(status!=pending)
- do something and release the lock

the logic is reliable in previous versions. but it breaks now.

**Comment by kyle-github** [comment] 2022-01-14 02:06
Can you capture log output from this and attach it to this issue?   Set the logging level to 4.   This will dump out (on stderr) a lot of information about what the library is doing internally.   If this is a command line tool, you can redirect the log:

```text
C:\my_tool.exe > log.txt 2>&1
```

With the extra locking you are doing, I am not sure what is happening here.   I have a similar test in C and I will instrument it to check the status to see if I see anything like this.

**Comment by Joylei** [comment] 2022-01-14 03:37
please find the attached log.
[log.txt](https://github.com/libplctag/libplctag/files/7867643/log.txt)

```txt
2022-01-14 11:32:24.754 thread(2) tag(0) DETAIL check_read_status_connected:1418 type byte = 196 (c4)
thread 'main' panicked at '2022-01-14 11:32:24.754 thread(2) tag(0) INFO check_read_status_connected:1479 Got 4 bytes of data
assertion failed: !status.is_pending()', E:\Dev\public\plctag-rs\crates\async\src\op.rs2022-01-14 11:32:24.754 thread
```

It seems libplctag works fine.   let me check what happened with my code.

another log
[log.txt](https://github.com/libplctag/libplctag/files/7867713/log.txt)

**Comment by Joylei** [comment] 2022-01-14 04:18
[log.txt](https://github.com/libplctag/libplctag/files/7867790/log.txt)

the args of callback of libplctag returns status=1
```
[2022-01-14T04:01:51Z DEBUG plctag_core::event] callback tag 24, event 2, status 1
2022-01-14 12:01:51.063 thread(3) tag(0) INFO recv_eip_response:1990  00 00 00 00 00 00 00 00 00 00
2022-01-14 12:01:51.063 thread(3) tag(0) INFO recv_eip_response:1990  02 00 a1 00 04 00 e1 7f 00 00
2022-01-14 12:01:51.063 thread(3) tag(0) INFO recv_eip_response:1990  b1 00 20 00 0b 00 8a 00 00 00
[2022-01-14T04:01:51Z DEBUG plctag_core::event] fetch handler in callback: Registry rw lock for tag 24
2022-01-14 12:01:51.063 thread(3) tag(0) INFO recv_eip_response:1990  02 00 06 00 10 00 d2 00 00 00
2022-01-14 12:01:51.063 thread(3) tag(0) INFO recv_eip_response:1990  c4 00 50 00 00 00 d2 00 00 00
thread 'main' panicked at 'assertion failed: !status.is_pending()', E:\Dev\public\plctag-rs\crates\async\src\op.rs
```

**Comment by kyle-github** [comment] 2022-01-14 04:41
I see the status in the log file.  This helps.  I am marking this as a bug.   I will need to trace through this to find out where the status is not being updated.     Strangely, I am not seeing this in my test program so I will need to reproduce this and make sure that I create a regression test for it.

**Comment by kyle-github** [comment] 2022-01-14 04:55
Going through the logs, it looks like the first read is the one that reports pending.   All the reads after that report PLCTAG_STATUS_OK.

This is likely to be a difference in the code that handles the first read which is triggered in plc_tag_create() to preload the tag data so that any metadata like the tag size is known before we could possibly write a value to the tag.

So there is something going on in that code path that is different.

It looks like you are using the non-blocking version of plc_tag_create()?

**Comment by Joylei** [comment] 2022-01-14 06:05
I'm using the non-blocking version of plc_tag_create(). the code loops wait until the status is not pending by polling plc_tag_status().

**Comment by kyle-github** [comment] 2022-01-15 02:00
Interesting.   This is odd because it means that the first read triggered by calling plc_tag_read() must be returned an event with the wrong status and not the internal read triggered on tag creation...   I will see if I can reproduce this locally.

**Comment by kyle-github** [comment] 2022-01-16 19:18
So far I am unable to reproduce this.   I have found a couple things with event handling that I am going to fix and maybe they will help?

There is one unsafe aspect that I found that may require that the callback is called with the tag's mutex (library internal) held.   If I cannot find a safe way around that, it will increase the possibility of deadlock.

**Comment by Joylei** [comment] 2022-01-17 05:12
I created some code for you to reproduce the bug in C.  It compiles on windows.
https://github.com/Joylei/libplctag/blob/bug-338/src/examples/callback_bug.c

To run the code, you need to modify the variable TAG_PATH accordingly.

**Comment by kyle-github** [comment] 2022-01-18 01:01
Thanks!  I will try to get this compiling as soon as my laptop is set up.  I got a Windows laptop today and am still getting it ready.

**Comment by kyle-github** [comment] 2022-01-27 02:22
I haven't forgotten about this.   Other, more urgent, problems came up.   I should be able to get back to this soon.

**Comment by kyle-github** [comment] 2022-02-02 05:07
I took a stab at this again.  I think I made it worse.   However, I now see the first create event and read completion event show PENDING status.  So this is reproducible.

**Comment by kyle-github** [comment] 2022-02-06 17:47
I added the code you provided for testing this, @Joylei.   I am testing on Windows.  I found a couple of things that were definitely wrong: I was synthesizing created events on read/write started events.   It should be only synthesized on read/write completed events.   Because of this, in some cases the created event was synthesized with the status of the read started event which was always PENDING.

Note that there is a new function, `tag_raise_event()` defined in src/lib/tag.h as a static inline function (essentially a type-safe macro) that does the synthesis now.   I removed all that from the generic handler.

I want to gather the events when there is no handler because there is no way to register a handler until after you call `plc_tag_create()`.   The generic dispatch/handler clears the events once it pushes them.  There is the risk that new events will overwrite old events (no queue), but the statuses should still be sane.

The code you provided is now in the `test_event_windows.c` example function.   

All these changes are now in the prerelease branch.

I went through the event test program carefully and noted that it will almost always decide that something is wrong because of what I think is a logic problem.   Rather than waking just the tag thread that was waiting for a read complete, it wakes all threads.   Many of those may not have received responses, so are still, correctly, sitting in a PENDING state.  Also, due to threading, the value of the status in the event and the value of the tag's status may have changed from each other by the time the tag thread wakes up.  The tag status in the callback is only valid as of the time the event is raised.   It may differ from the tag's status by the time the callback is called.

I changed the code so that it uses the new extended callback function introduced in 2.5.0 and the behavior is different.   It now only wakes one thread when the callback is called.  However, I still see some interesting things.

I still see the error "something is wrong..." but it looks like the underlying problem now is that the status of the tag is good when the callback is called, but has changed to PENDING by the time the thread wakes up.  I cannot figure out why that is happening.   It looks like there is a pending read already queued and when that read kicks off the tag state is set to PENDING.   This appears to be happening between the time the tag callback is called and the time the tag thread wakes up.

Can you please look at the prerelease branch again and check the code in `test_event_windows.c`?   I am not a Windows programmer, so I may have not understood what the code is doing.   That said, the remaining checks appear to be comparing the state as of the time thread wakes which may have changed from the time the event was raised and the time the event callback was run.  One thing I may try is to store the status from the callback into the tag status structure and make sure that was PLCTAG_STATUS_OK rather than the current tag state.

**Comment by Joylei** [comment] 2022-02-06 21:42
Do not mind the ugly code I provided for reproduce. 

It's not a threading or synchronization issue. It complains "something is wrong" because the status is pending but it should not be.
I have explained what happened in [#350](https://github.com/libplctag/libplctag/pull/350#issuecomment-1030773056).

I try to explain it again here.
Assume that we do not register a callback or we have unregistered the callback. 
- we perform a `read`, and `READ_COMPLETED` event has been raised, now we have `tag-> event_read_complete=1`.
- we register a callback
- we perform a `read` again, we'll get a event `READ_STARTED`; because of `tag-> event_read_complete=1`, we'll get a event `READ_COMPLETED` at the same time(which is wrong, we are in the state of reading).

A quick dirty fix just for reproduce code would be:
```C
void plc_tag_generic_handle_event_callbacks(plc_tag_p tag){
   if(tag){
        if (tag->callback){
              //old code ...
        } else {
              if (tag-> event_read_complete ){
                    tag-> event_read_complete = 0;
              }
        }
   }
}
```

But the root cause is that the code will not reset event_read_complete and other similar flags if there is no callback.
It's better to fix such issue in `tag_raise_event()`.

**Comment by Joylei** [comment] 2022-02-06 22:18
> I want to gather the events when there is no handler because there is no way to register a handler until after you call plc_tag_create(). The generic dispatch/handler clears the events once it pushes them. There is the risk that new events will overwrite old events (no queue), but the statuses should still be sane.

I understand what you're trying to do. But events are some kind of mutually exclusive. It should not raise a `READ_STARTED`, `READ_COMPLETED`, `WRITE_STARTED`, `WRITE_COMLETED` at the same time. Usually we only care about events that happens after we register a callback. We do not need to replay the past.

We might need a `plc_tag_create_ex()` to pass a callback?

**Comment by kyle-github** [comment] 2022-02-07 01:45
I also was thinking about creating a `plc_tag_create_ex()` function that takes the callback and extra argument.   That's the only way to make sure that you have a callback when an event is raised early in the creation process.   

For the use cases that users have communicated to me, things like CREATED events are very important.   If events are not captured until there is a callback, then the CREATED event will be of little use.

I am going to try with an extended `plc_tag_create_ex()` function to see what that does to the UX (user experience).

**Comment by kyle-github** [comment] 2022-02-07 05:01
I am generating some of the events twice, it appears.   I need to fix that before I check this in.

**Comment by kyle-github** [comment] 2022-02-09 01:40
The fix for the duplicate events is now checked in.   This is as far as I am going to go with event handling until I refactor the Rockwell code to use the same overall pattern as the Modbus code.   There are too many partial state machines.

I added a new function, `plc_tag_create_ex()`, that takes an additional callback and user data pointer as we discussed earlier.   I also updated the `test_callback_ex.c` program to use it.

Events are ignored until there is a callback.

**Comment by kyle-github** [comment] 2022-02-09 01:40
Can you please test the prerelease branch?

**Comment by Joylei** [comment] 2022-02-09 03:56
I'm trying. but I'm entering a infinite loop
`while ((rc = plc_tag_status(tag)) == PLCTAG_STATUS_PENDING)`.
let me check what's wrong.

**Comment by Joylei** [comment] 2022-02-09 04:10
It's my network.
Looks OK.

**Comment by kyle-github** [comment] 2022-02-09 04:32
Thanks for testing!

**Comment by kyle-github** [comment] 2022-02-14 00:47
Sorry for the delay.  I found out today that the PLCTAG_EVENT_DELETED events are not propagating correctly.   Need to fix that before release.

**Closed as completed** 2022-02-14 02:59 UTC
Labels: bug, question
